### ISSUE TITLE
Confused with parameters 

### ISSUE THREAD

**Issue by manpreet-tolexo** [nightw/mikoomi-zabbix-mongodb-monitoring#6] opened 2016-01-25 07:41 UTC
having trouble posting to zabbix server everything is getting collected in .data file but nothing is being sent to server

**Comment by nightw** [comment] 2016-01-25 23:49
Hi @manpreet-tolexo,

I think you should check the log file which is most likely `/tmp/mikoomi-mongodb-plugin.php_<your_zabbix>_name.log`. It may contain some information on what went wrong.

If that does not help you can try to send the `.data` file to Zabbix manually using this part of the code with the right parameters: `zabbix_sender -vv -z <zabbix_server_ip> -p <zabbix_server_port. -i <data_file_path>`. I've encountered errors with `zabbix_sender` before which were caused by a single missing value from the data file (not 3 items in a line, but 2) and it did not log anything, just did not send the values. So checking the `.data` file manually for possible errors could help also.

Also please make sure that the Zabbix server has the right Template attached to the right Host so the values can be sent to Zabbix at all.

**Comment by manpreet-tolexo** [comment] 2016-01-26 07:00
I think i found the problem . the problemw as at line 480. The script 
would just die

On Tuesday 26 January 2016 05:19 AM, Pal David GERGELY wrote:
>
> Hi @manpreet-tolexo <https://github.com/manpreet-tolexo>,
>
> I think you should check the log file which is most likely 
> |/tmp/mikoomi-mongodb-plugin.php_<your_zabbix>_name.log|. It may 
> contain some information on what went wrong.
>
> If that does not help you can try to send the |.data| file to Zabbix 
> manually using this part of the code with the right parameters: 
> |zabbix_sender -vv -z <zabbix_server_ip> -p <zabbix_server_port. -i 
> <data_file_path>|. I've encountered errors with |zabbix_sender| before 
> which were caused by a single missing value from the data file (not 3 
> items in a line, but 2) and it did not log anything, just did not send 
> the values. So checking the |.data| file manually for possible errors 
> could help also.
>
> Also please make sure that the Zabbix server has the right Template 
> attached to the right Host so the values can be sent to Zabbix at all.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nightw/mikoomi-zabbix-mongodb-monitoring/issues/6#issuecomment-174734080>.
>


-- 
*Happy Republic Day*

[image: Tolexo] <http://www.tolexo.com>
India's Largest Marketplace for Business Goods & Supplies
Download Tolexo app: 
<https://play.google.com/store/apps/details?id=com.tolexo.android>  
<https://itunes.apple.com/in/app/tolexo-online-b2b-shopping/id1069596004>
[image: CNBC Video] <https://www.youtube.com/watch?v=7VVHMq9WPzk> 

Watch Tolexo on CNBC Awaaz Entrepreneur 
<https://www.youtube.com/watch?v=7VVHMq9WPzk>

Exclusive interview with *Mr. Brijesh Agarwal* (CEO, Tolexo.com)

For more updates visit our Press Section <http://www.tolexo.com/press.html>
[image: facebook] <https://www.facebook.com/tolexo> [image: facebook] 
<https://plus.google.com/+TolexoIndia/> [image: facebook] 
<https://www.linkedin.com/company/tolexo-com> [image: facebook] 
<https://twitter.com/tolexo>

**Comment by nightw** [comment] 2016-01-26 23:10
You mean this line, right? https://github.com/nightw/mikoomi-zabbix-mongodb-monitoring/blob/master/mikoomi-mongodb-plugin.php#L480

In this case my best guess is that you do not have enough access rights in the MongoDB instance with the given user to read the `oplog.rs` collection in the `local` database.

You could try to run in the in the mongo command line with the same user to see what happens:
```
use local
db.oplog.rs.count()
db.oplog.rs.findOne()
```

**Comment by manpreet-tolexo** [comment] 2016-01-27 03:58
Ah, I think maybe that's the case, What rights would be required to 
execute those commands, Currently i have given clusterMonitor and 
hostManager aCLs to the user running those commands.

On Wednesday 27 January 2016 04:40 AM, Pal David GERGELY wrote:
>
> You mean this line, right? 
> https://github.com/nightw/mikoomi-zabbix-mongodb-monitoring/blob/master/mikoomi-mongodb-plugin.php#L480
>
> In this case my best guess is that you do not have enough access 
> rights in the MongoDB instance with the given user to read the 
> |oplog.rs| collection in the |local| database.
>
> You could try to run in the in the mongo command line with the same 
> user to see what happens:
>
> |use local db.oplog.rs.count() db.oplog.rs.findOne() |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nightw/mikoomi-zabbix-mongodb-monitoring/issues/6#issuecomment-175287484>.
>


-- 
*Happy Republic Day*

[image: Tolexo] <http://www.tolexo.com>
India's Largest Marketplace for Business Goods & Supplies
Download Tolexo app: 
<https://play.google.com/store/apps/details?id=com.tolexo.android>  
<https://itunes.apple.com/in/app/tolexo-online-b2b-shopping/id1069596004>
[image: CNBC Video] <https://www.youtube.com/watch?v=7VVHMq9WPzk> 

Watch Tolexo on CNBC Awaaz Entrepreneur 
<https://www.youtube.com/watch?v=7VVHMq9WPzk>

Exclusive interview with *Mr. Brijesh Agarwal* (CEO, Tolexo.com)

For more updates visit our Press Section <http://www.tolexo.com/press.html>
[image: facebook] <https://www.facebook.com/tolexo> [image: facebook] 
<https://plus.google.com/+TolexoIndia/> [image: facebook] 
<https://www.linkedin.com/company/tolexo-com> [image: facebook] 
<https://twitter.com/tolexo>

**Comment by nightw** [comment] 2016-01-31 22:55
I am not exactly sure, but my guess is that the user does not need a "global" or bult-in role, just the `find` right to the `local` database (which you can achieve for example by creating a custom role and adding the monitoring user to it). So the main point is to grant access to the collection itself, which is in the `local` database and called `oplog.rs`

**Comment by laozhizi** [comment] 2016-02-25 07:54
db.oplog.rs.count()
2016-02-25T15:53:19.912+0800 E QUERY    Error: error: { "$err" : "can't use 'local' database through mongos", "code" : 13644 }
    at Error (<anonymous>)
    at DBQuery.next (src/mongo/shell/query.js:259:15)
    at DBCollection.findOne (src/mongo/shell/collection.js:189:22)
    at DB.runCommand (src/mongo/shell/db.js:58:41)
    at DBQuery.count (src/mongo/shell/query.js:324:24)
    at DBCollection.count (src/mongo/shell/collection.js:1046:27)
    at (shell):1:13 at src/mongo/shell/query.js:259

**Comment by nightw** [comment] 2016-02-25 22:01
@laozhizi I am not sure what do you want to ask. :)

But my wild guess is that your problem is that you try to monitor a `mongos` instance instead of a MongoDB server/shard/node. And a `mongos` instance really don't have a `local` database.

See here: http://stackoverflow.com/questions/31835075/how-look-at-oplog-in-mongodb-with-sharding

Also I think I will close this issue, since there were no update on my last suggestion to @manpreet-tolexo and this last comment was a new, unrelated thing.

**Closed by nightw** 2016-02-25 22:01 UTC

**Comment by laozhizi** [comment] 2016-02-26 03:32
You got it。

**Comment by laozhizi** [comment] 2016-05-25 15:26
write_to_log_file(line 82) should be write_to_data_lines.

**Comment by nightw** [comment] 2016-05-29 21:29
@laozhizi Let's talk about this in the separate issue for this: #10
