### ISSUE TITLE
Issues with Seeing latest data + No Logging

### ISSUE THREAD

**Issue by DanielMabbett** [nightw/mikoomi-zabbix-mongodb-monitoring#19] opened 2017-04-27 15:53 UTC
Hi Guys,

I am using this but cant seem to see any of the latest data:
![screen shot 2017-04-27 at 16 43 10](https://cloud.githubusercontent.com/assets/15195905/25491691/a2622ac2-2b68-11e7-8929-88ca1e0191e9.png)

_sh mikoomi-mongodb-plugin-32.sh -D -z MONGOSERVERNAME -u MONGOUSER -x MONGOPASSWORD -H ZABBIXIP -P ZABBIXPORT_

There is actually no logging coming through to /tmp/ as shown in README 

Also getenforce is set to 0 (Disabled)

Any help?

**Comment by nightw** [comment] 2017-05-03 20:55
@ExplodingTurkey Could you tell me more about the MongoDB version and the PHP version you're trying this with.

I think the script does not support PHP 7 as it can be seen in this issue: #16

**Comment by tahz7** [comment] 2017-06-27 11:10
Hey,

Seeing the same issue. We're using mongodb 3.4, PHP 5.4.16.

When running the script initially we were getting the following error;

```PHP Fatal error:  Class 'MongoClient' not found in /home/test/mongodb-stuff/mikoomi-mongodb-plugin-32.php on line 145

Fatal error: Class 'MongoClient' not found in /home/tahzeem.taj/mongodb-stuff/mikoomi-mongodb-plugin-32.php on line 145
```

I changed this line and instead added;

`$mongo_connection = new MongoDB\Driver\Manager("mongodb://$connect_string") ;`

Which connected, but gave further errors like;

```mikoomi-mongodb-plugin-32.php: Successfully connected to mongoDB using connect string dataadmin:datsAMongo@localhost:27017

PHP Fatal error:  Call to undefined method MongoDB\Driver\Manager::selectDB() in /home/tahzeem.taj/mongodb-stuff/mikoomi-mongodb-plugin-32.php on line 161

Fatal error: Call to undefined method MongoDB\Driver\Manager::selectDB() in /home/tahzeem.taj/mongodb-stuff/mikoomi-mongodb-plugin-32.php on line 161
```

The script isn't compatible with mongo 3.4, is there any simple fix for this or would it require a complete rewrite?

**Comment by nightw** [comment] 2017-06-28 18:48
I think the problem is not with MongoDB 3.4, but the PHP module on your part. If you check the documentation [here](http://php.net/manual/en/class.mongodb.php) it says the if you use the PECL module for MongoDB version `0.9` or higher has the `MongoClient` class. I think that you're trying to use [this](http://php.net/manual/en/set.mongodb.php) built-in MongoDB driver, which is not what the code is written for.

**Closed as completed** 2019-07-25 08:58 UTC
